<% Response.WriteFile("header.aspx") %>

<div class="contenedor1140 padding16">
  <h2 class="azul">Políticas de privacidad</h2>
  <div>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at cursus mauris. Nulla et turpis enim. Integer consectetur diam sit amet nulla feugiat, eu tincidunt mauris pulvinar. Nullam pulvinar mauris neque, vitae lacinia diam dignissim non. Nunc facilisis mauris risus, blandit laoreet nulla scelerisque ac. Nunc felis quam, aliquet a aliquet vestibulum, facilisis et lorem. Donec facilisis dictum elit. In sed dui sem. Morbi nulla risus, varius ut felis sit amet, elementum feugiat augue.<br>
  <br>
  Mauris vitae nisi mollis, ultrices turpis quis, sollicitudin orci. Proin ligula mi, aliquet vel magna in, dignissim auctor nunc. Praesent porttitor commodo lorem sed cursus. Morbi erat sem, interdum convallis suscipit id, dapibus eget leo. Mauris eu commodo purus. Fusce id dolor elementum, convallis urna et, aliquam odio. In mattis enim nisi, et bibendum lacus consequat in. Sed vel sem in felis pellentesque suscipit ut sit amet purus. Nam fringilla rutrum elit, in luctus purus porttitor ac. Nunc in rhoncus elit. Nulla venenatis sapien eget purus efficitur semper. Phasellus ornare ipsum vitae enim placerat, ut vulputate augue convallis. Vestibulum at nibh gravida, blandit augue a, elementum est. Nullam bibendum quis magna et posuere. Proin lorem eros, convallis eu purus eu, mollis dignissim mi. Praesent tincidunt dignissim felis ut hendrerit.    <br>
  <br>
  Ut nec ipsum non eros maximus sodales. Praesent laoreet dui justo, vel eleifend felis molestie id. Morbi commodo non libero vitae sagittis. Fusce at vestibulum elit. Nullam nec massa ante. Aliquam a hendrerit lorem. Mauris gravida egestas metus, sit amet ultricies libero elementum eget. Quisque viverra, leo sit amet laoreet scelerisque, dui mi feugiat nibh, sit amet condimentum enim purus vel sem. Quisque eu semper mi, non molestie purus.    <br>
  <br>
  Nulla lorem urna, vehicula id semper volutpat, facilisis a erat. Fusce aliquet, odio ac facilisis consectetur, mi nulla ultricies nibh, in dictum sapien risus in nibh. Curabitur at ligula sollicitudin, maximus dui in, rutrum ex. Morbi a metus interdum, vulputate justo in, tristique velit. Etiam volutpat tortor ut cursus imperdiet. Morbi nec iaculis tortor. In laoreet, est suscipit posuere elementum, sem enim malesuada magna, eu viverra nunc velit at arcu. Nunc volutpat, magna in eleifend porta, tellus turpis porttitor turpis, sed interdum lacus metus a velit. Quisque in diam sapien. Vivamus pretium risus non nulla efficitur, ut fermentum velit placerat. Fusce viverra, neque et eleifend pretium, lectus diam bibendum nisi, non scelerisque tortor sem vitae nibh. Vivamus sed nibh quis tellus interdum ultrices in vel leo. Maecenas eu lacus diam. Vivamus sodales aliquet metus suscipit euismod.    <br>
  <br>
  Vivamus ornare mi leo, tempor volutpat est dictum ac. Ut egestas bibendum dolor, vel porttitor nisi ultricies ac. Phasellus ullamcorper purus purus, a iaculis lorem consectetur vel. In tincidunt neque in nibh vestibulum, et cursus nisl fringilla. Donec metus dui, consequat quis vulputate in, sodales vel ipsum. Curabitur metus felis, egestas ac felis eget, luctus rhoncus enim. Suspendisse aliquet dapibus ultrices. Duis tincidunt gravida turpis, ac interdum metus tempor ut. Nunc tempus orci eu sollicitudin pharetra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi ac enim sed nibh convallis porttitor eu in velit.    <br>
  <br>
  Donec in dolor at nulla tristique vulputate. Morbi bibendum bibendum dui, nec commodo mi. Praesent porttitor cursus dictum. Pellentesque a porta nunc. Vestibulum eu leo maximus, eleifend odio cursus, hendrerit orci. Nam eget mi in enim pretium scelerisque. Nullam placerat, magna id aliquam lobortis, mauris ex lacinia nisi, eget lacinia tellus ex vel nulla. Vestibulum a nunc id diam venenatis ornare. Pellentesque vel volutpat est, ut ullamcorper nisi. Pellentesque suscipit, sapien vel feugiat interdum, nisl sem pulvinar elit, a egestas enim libero tincidunt mi. Etiam in eros in lorem dapibus fringilla vel et metus.    <br>
  <br>
  Vestibulum ut mauris quis orci porta volutpat. Pellentesque odio nunc, feugiat nec placerat vel, elementum eu felis. Donec dignissim gravida mi, at mollis leo viverra ut. Quisque ullamcorper ornare arcu, auctor eleifend eros. Fusce sit amet tortor mauris. Donec ornare egestas nunc, in lobortis quam hendrerit quis. Praesent convallis eros dui, a venenatis justo pharetra vel. Nullam quis leo id massa imperdiet placerat. Nunc faucibus, velit non scelerisque molestie, felis magna volutpat justo, sit amet hendrerit nunc mi tincidunt odio. Ut ac imperdiet arcu. Aliquam erat volutpat. Nulla consectetur laoreet est vel maximus.    <br>
  <br>
  <p>Nulla urna nisi, molestie vel consectetur non, ornare ultrices nulla. Sed eleifend lacus non diam vehicula, eu mattis libero dignissim. Aliquam tempor, dolor lacinia gravida scelerisque, nisi ex vulputate nibh, non vulputate velit sem nec nulla. Sed eu elit mattis diam faucibus luctus. Curabitur eu pharetra ipsum. Nunc eget porta mi. Vivamus cursus sed metus a mattis. Nulla facilisi. Praesent non odio metus.</p>
  <p>Cras ac pulvinar felis. Integer viverra porta congue. Aenean convallis mollis risus quis faucibus. Aenean pulvinar ut sem at malesuada. Pellentesque vel pharetra justo. Suspendisse aliquam, nulla non tincidunt vehicula, nibh tortor consectetur metus, ut iaculis tellus tortor id odio. Nulla ultrices ligula mi, vitae iaculis tellus euismod vitae. Ut et mi at turpis pharetra mattis id at risus. In posuere sem ut egestas efficitur. Suspendisse potenti. Integer eu ligula imperdiet, dapibus nunc vel, pellentesque enim. Fusce mollis, odio quis sodales luctus, nulla nibh malesuada tortor, a bibendum ligula odio ac dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce non sagittis quam.</p>
  <p>Sed gravida quam arcu. Mauris at rutrum mauris, ut pharetra metus. Integer semper mauris mauris, sit amet eleifend mauris egestas a. In ac sodales purus. Nunc justo arcu, tincidunt ac sapien in, sodales vulputate urna. Cras in ullamcorper ligula. Curabitur consectetur, ex sit amet fermentum luctus, quam tortor rutrum mi, at eleifend enim sem quis velit. Suspendisse feugiat convallis luctus. Maecenas id metus eu odio convallis lobortis ac ut metus. Fusce eu leo blandit, elementum velit eget, sodales ante.</p>
  </div>
</div>

<% Response.WriteFile("footer.aspx") %>